# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectile_movement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import numpy as np
import math as math

def v(a, v_0, t):
    return a*t + v_0

def s(a, v_0, s_0, t):
    return a/2*t**2 + v_0*t + s_0



# this is the main window class

class Ui_MainWindow(object):

# setup the main window
# =====================================================
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.a_x = QtWidgets.QTextEdit(self.centralwidget)
        self.a_x.setEnabled(True)
        self.a_x.setGeometry(QtCore.QRect(220, 70, 251, 61))
# the default font or sth
# =====================================================
        font = QtGui.QFont()
        font.setFamily("Adobe Myungjo Std")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
# these are the features in the main window
# =====================================================

        self.a_x_label = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label.setGeometry(QtCore.QRect(80, 70, 121, 61))
        self.a_x_label.setFont(font)
        self.a_x_label.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label.setLineWidth(5)
        self.a_x_label.setObjectName("a_x_label")

        self.a_x_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label_2.setGeometry(QtCore.QRect(80, 150, 121, 61))
        self.a_x_label_2.setFont(font)
        self.a_x_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label_2.setLineWidth(5)
        self.a_x_label_2.setObjectName("a_x_label_2")

        self.a_x_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label_3.setGeometry(QtCore.QRect(80, 390, 121, 61))
        self.a_x_label_3.setFont(font)
        self.a_x_label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label_3.setLineWidth(5)
        self.a_x_label_3.setObjectName("a_x_label_3")

        self.a_x_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label_4.setGeometry(QtCore.QRect(80, 310, 121, 61))
        self.a_x_label_4.setFont(font)
        self.a_x_label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label_4.setLineWidth(5)
        self.a_x_label_4.setObjectName("a_x_label_4")

        self.a_x_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label_5.setGeometry(QtCore.QRect(80, 230, 121, 61))
        self.a_x_label_5.setFont(font)
        self.a_x_label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label_5.setLineWidth(5)
        self.a_x_label_5.setObjectName("a_x_label_5")

        self.a_x_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.a_x_label_6.setGeometry(QtCore.QRect(80, 470, 121, 61))
        self.a_x_label_6.setFont(font)
        self.a_x_label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x_label_6.setLineWidth(5)
        self.a_x_label_6.setObjectName("a_x_label_6")

        font.setBold(False)
        font.setPointSize(16)
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(510, 40, 551, 271))
        self.info.setFont(font)
        self.info.setObjectName("info")


        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(180, 560, 151, 71))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/Wallpaper/icon/comstockunlimited1257437.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calcButton.setIcon(icon)
        self.calcButton.setIconSize(QtCore.QSize(50, 50))
        self.calcButton.setObjectName("calcButton")
        

        self.y_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.y_0.setEnabled(True)
        self.y_0.setGeometry(QtCore.QRect(220, 470, 251, 61))
        self.y_0.setFont(font)
        self.y_0.setFrameShape(QtWidgets.QFrame.Box)
        self.y_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.y_0.setLineWidth(5)
        self.y_0.setMidLineWidth(0)
        self.y_0.setObjectName("y_0")
        self.y_0.setText('0')

        self.x_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.x_0.setEnabled(True)
        self.x_0.setGeometry(QtCore.QRect(220, 390, 251, 61))
        self.x_0.setFont(font)
        self.x_0.setFrameShape(QtWidgets.QFrame.Box)
        self.x_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.x_0.setLineWidth(5)
        self.x_0.setMidLineWidth(0)
        self.x_0.setObjectName("x_0")
        self.x_0.setText("0")

        self.v_y_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.v_y_0.setEnabled(True)
        self.v_y_0.setGeometry(QtCore.QRect(220, 310, 251, 61))
        self.v_y_0.setFont(font)
        self.v_y_0.setFrameShape(QtWidgets.QFrame.Box)
        self.v_y_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v_y_0.setLineWidth(5)
        self.v_y_0.setMidLineWidth(0)
        self.v_y_0.setObjectName("v_y_0")
        self.v_y_0.setText("0")

        self.v_x_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.v_x_0.setEnabled(True)
        self.v_x_0.setGeometry(QtCore.QRect(220, 230, 251, 61))
        self.v_x_0.setFont(font)
        self.v_x_0.setFrameShape(QtWidgets.QFrame.Box)
        self.v_x_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v_x_0.setLineWidth(5)
        self.v_x_0.setMidLineWidth(0)
        self.v_x_0.setObjectName("v_x_0")
        self.v_x_0.setText("0")

        self.a_y = QtWidgets.QTextEdit(self.centralwidget)
        self.a_y.setEnabled(True)
        self.a_y.setGeometry(QtCore.QRect(220, 150, 251, 61))
        self.a_y.setFont(font)
        self.a_y.setFrameShape(QtWidgets.QFrame.Box)
        self.a_y.setFrameShadow(QtWidgets.QFrame.Plain)
        self.a_y.setLineWidth(5)
        self.a_y.setMidLineWidth(0)
        self.a_y.setObjectName("a_y")
        self.a_y.setText("-9.81")

        self.a_x.setFont(font)
        self.a_x.setFrameShape(QtWidgets.QFrame.Box)
        self.a_x.setFrameShadow(QtWidgets.QFrame.Plain)
        self.a_x.setLineWidth(5)
        self.a_x.setMidLineWidth(0)
        self.a_x.setObjectName("a_x")
        self.a_x.setText('0')
        self.a_x.value = int(self.a_x.toPlainText())

# =====================================================
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.calcButton.clicked.connect(lambda: self.calc())
        
# the texts in the ui or sth
# =====================================================
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.a_x_label.setText(_translate("MainWindow", "a_x"))
        self.a_x_label_2.setText(_translate("MainWindow", "a_y"))
        self.a_x_label_3.setText(_translate("MainWindow", "x_0"))
        self.a_x_label_4.setText(_translate("MainWindow", "v_y_0"))
        self.a_x_label_5.setText(_translate("MainWindow", "v_x_0"))
        self.a_x_label_6.setText(_translate("MainWindow", "y_0"))
        self.info.setText(_translate("MainWindow", "this app is for caculating projectile\n"
"movement with constant acceleration,\n"
"please enter \"V_x_0, V_y_0, x_0 and\n"
" y_0\" to see the results (all constants).\n"
" \"a_x\" and \"a_y\" are set by default to \n"
"0 and -9.81. you can change them if \n"
"necessary"))
        self.calcButton.setText(_translate("MainWindow", "calculate "))
        self.calcButton.setShortcut(_translate("MainWindow", "Return"))

    def calc(self):
        pass



# ===================================================
# ===================================================
# this is the output window ui
# ===================================================
class Ui_outputs(object):
# these are the features of the output window
# ===================================================
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 437)
        self.range_label = QtWidgets.QLabel(Form)
        self.range_label.setGeometry(QtCore.QRect(20, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.range_label.setFont(font)
        self.range_label.setFrameShape(QtWidgets.QFrame.Box)
        self.range_label.setLineWidth(3)
        self.range_label.setObjectName("range_label")
        self.range = QtWidgets.QLabel(Form)
        self.range.setGeometry(QtCore.QRect(180, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.range.setFont(font)
        self.range.setFrameShape(QtWidgets.QFrame.Box)
        self.range.setLineWidth(3)
        self.range.setObjectName("range")
        self.V_highest_x_label = QtWidgets.QLabel(Form)
        self.V_highest_x_label.setGeometry(QtCore.QRect(410, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_highest_x_label.setFont(font)
        self.V_highest_x_label.setFrameShape(QtWidgets.QFrame.Box)
        self.V_highest_x_label.setLineWidth(3)
        self.V_highest_x_label.setObjectName("V_highest_x_label")
        self.V_highest_x = QtWidgets.QLabel(Form)
        self.V_highest_x.setGeometry(QtCore.QRect(570, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_highest_x.setFont(font)
        self.V_highest_x.setFrameShape(QtWidgets.QFrame.Box)
        self.V_highest_x.setLineWidth(3)
        self.V_highest_x.setObjectName("V_highest_x")
        self.V_highest_y = QtWidgets.QLabel(Form)
        self.V_highest_y.setGeometry(QtCore.QRect(570, 110, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_highest_y.setFont(font)
        self.V_highest_y.setFrameShape(QtWidgets.QFrame.Box)
        self.V_highest_y.setLineWidth(3)
        self.V_highest_y.setObjectName("V_highest_y")
        self.V_final_x_label = QtWidgets.QLabel(Form)
        self.V_final_x_label.setGeometry(QtCore.QRect(20, 110, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_final_x_label.setFont(font)
        self.V_final_x_label.setFrameShape(QtWidgets.QFrame.Box)
        self.V_final_x_label.setLineWidth(3)
        self.V_final_x_label.setObjectName("V_final_x_label")
        self.V_highest_y_label = QtWidgets.QLabel(Form)
        self.V_highest_y_label.setGeometry(QtCore.QRect(410, 110, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_highest_y_label.setFont(font)
        self.V_highest_y_label.setFrameShape(QtWidgets.QFrame.Box)
        self.V_highest_y_label.setLineWidth(3)
        self.V_highest_y_label.setObjectName("V_highest_y_label")
        self.V_final_x = QtWidgets.QLabel(Form)
        self.V_final_x.setGeometry(QtCore.QRect(180, 110, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_final_x.setFont(font)
        self.V_final_x.setFrameShape(QtWidgets.QFrame.Box)
        self.V_final_x.setLineWidth(3)
        self.V_final_x.setObjectName("V_final_x")
        self.x_highest = QtWidgets.QLabel(Form)
        self.x_highest.setGeometry(QtCore.QRect(570, 190, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.x_highest.setFont(font)
        self.x_highest.setFrameShape(QtWidgets.QFrame.Box)
        self.x_highest.setLineWidth(3)
        self.x_highest.setObjectName("x_highest")
        self.V_final_y_label = QtWidgets.QLabel(Form)
        self.V_final_y_label.setGeometry(QtCore.QRect(20, 190, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_final_y_label.setFont(font)
        self.V_final_y_label.setFrameShape(QtWidgets.QFrame.Box)
        self.V_final_y_label.setLineWidth(3)
        self.V_final_y_label.setObjectName("V_final_y_label")
        self.x_highest_label = QtWidgets.QLabel(Form)
        self.x_highest_label.setGeometry(QtCore.QRect(410, 190, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.x_highest_label.setFont(font)
        self.x_highest_label.setFrameShape(QtWidgets.QFrame.Box)
        self.x_highest_label.setLineWidth(3)
        self.x_highest_label.setObjectName("x_highest_label")
        self.V_final_y = QtWidgets.QLabel(Form)
        self.V_final_y.setGeometry(QtCore.QRect(180, 190, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.V_final_y.setFont(font)
        self.V_final_y.setFrameShape(QtWidgets.QFrame.Box)
        self.V_final_y.setLineWidth(3)
        self.V_final_y.setObjectName("V_final_y")
        self.y_highest = QtWidgets.QLabel(Form)
        self.y_highest.setGeometry(QtCore.QRect(570, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.y_highest.setFont(font)
        self.y_highest.setFrameShape(QtWidgets.QFrame.Box)
        self.y_highest.setLineWidth(3)
        self.y_highest.setObjectName("y_highest")
        self.t_final_label = QtWidgets.QLabel(Form)
        self.t_final_label.setGeometry(QtCore.QRect(20, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.t_final_label.setFont(font)
        self.t_final_label.setFrameShape(QtWidgets.QFrame.Box)
        self.t_final_label.setLineWidth(3)
        self.t_final_label.setObjectName("t_final_label")
        self.y_highest_label = QtWidgets.QLabel(Form)
        self.y_highest_label.setGeometry(QtCore.QRect(410, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.y_highest_label.setFont(font)
        self.y_highest_label.setFrameShape(QtWidgets.QFrame.Box)
        self.y_highest_label.setLineWidth(3)
        self.y_highest_label.setObjectName("y_highest_label")
        self.t_final = QtWidgets.QLabel(Form)
        self.t_final.setGeometry(QtCore.QRect(180, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.t_final.setFont(font)
        self.t_final.setFrameShape(QtWidgets.QFrame.Box)
        self.t_final.setLineWidth(3)
        self.t_final.setObjectName("t_final")
        self.t_highest = QtWidgets.QLabel(Form)
        self.t_highest.setGeometry(QtCore.QRect(570, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.t_highest.setFont(font)
        self.t_highest.setFrameShape(QtWidgets.QFrame.Box)
        self.t_highest.setLineWidth(3)
        self.t_highest.setObjectName("t_highest")
        self.initial_theta_label = QtWidgets.QLabel(Form)
        self.initial_theta_label.setGeometry(QtCore.QRect(20, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.initial_theta_label.setFont(font)
        self.initial_theta_label.setFrameShape(QtWidgets.QFrame.Box)
        self.initial_theta_label.setLineWidth(3)
        self.initial_theta_label.setObjectName("initial_theta_label")
        self.t_highest_label = QtWidgets.QLabel(Form)
        self.t_highest_label.setGeometry(QtCore.QRect(410, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.t_highest_label.setFont(font)
        self.t_highest_label.setFrameShape(QtWidgets.QFrame.Box)
        self.t_highest_label.setLineWidth(3)
        self.t_highest_label.setObjectName("t_highest_label")
        self.initial_theta = QtWidgets.QLabel(Form)
        self.initial_theta.setGeometry(QtCore.QRect(180, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.initial_theta.setFont(font)
        self.initial_theta.setFrameShape(QtWidgets.QFrame.Box)
        self.initial_theta.setLineWidth(3)
        self.initial_theta.setObjectName("initial_theta")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 50, 31, 361))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


# ===================================================
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.range_label.setText(_translate("Form", "range:"))
        self.range.setText(_translate("Form", "range"))
        self.V_highest_x_label.setText(_translate("Form", "V_highest_x"))
        self.V_highest_x.setText(_translate("Form", "V_highest_x"))
        self.V_highest_y.setText(_translate("Form", "V_highest_y"))
        self.V_final_x_label.setText(_translate("Form", "V_final_x:"))
        self.V_highest_y_label.setText(_translate("Form", "V_highest_y"))
        self.V_final_x.setText(_translate("Form", "V_final_x"))
        self.x_highest.setText(_translate("Form", "x_highest"))
        self.V_final_y_label.setText(_translate("Form", "V_final_y:"))
        self.x_highest_label.setText(_translate("Form", "x_highest:"))
        self.V_final_y.setText(_translate("Form", "V_final_y"))
        self.y_highest.setText(_translate("Form", "y_highest"))
        self.t_final_label.setText(_translate("Form", "t_final:"))
        self.y_highest_label.setText(_translate("Form", "y_highest:"))
        self.t_final.setText(_translate("Form", "t_final"))
        self.t_highest.setText(_translate("Form", "t_highest"))
        self.initial_theta_label.setText(_translate("Form", "initial_theta:"))
        self.t_highest_label.setText(_translate("Form", "t_highest:"))
        self.initial_theta.setText(_translate("Form", "initial_theta"))
        self.label.setText(_translate("Form", "O\n"
"U\n"
"T\n"
"P\n"
"U\n"
"T\n"
"S"))


class Form(QtWidgets.QWidget, Ui_outputs):
    def __init__(self, *args, **kwargs):
        QtWidgets.QWidget.__init__(self, *args, **kwargs)
        self.setupUi(self)

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, **kwargs):
        QtWidgets.QMainWindow.__init__(self, *args, **kwargs)
        self.setupUi(self)
        self.calcButton.clicked.connect(self.onClicked)

    def onClicked(self):
        # actual calculations

        a_x = float(self.a_x.toPlainText())
        a_y = float(self.a_y.toPlainText())
        v_x_0 = float(self.v_x_0.toPlainText())
        v_y_0 = float(self.v_y_0.toPlainText())
        x_0 = float(self.x_0.toPlainText())
        y_0 = float(self.y_0.toPlainText())
        t_final = -2*v_y_0/a_y
        x_final = s(a_x, v_x_0, x_0, t_final)
        V_final_x = v(a_x, v_x_0, t_final)
        V_final_y = v(a_y, v_y_0, t_final)

        t_highest = -v_y_0/a_y

        V_highest_x = v(a_x, v_x_0, t_highest)
        V_highest_y = v(a_y, v_y_0, t_highest)
        x_highest = s(a_x, v_x_0, x_0, t_highest)
        y_highest = s(a_y, v_y_0, y_0, t_highest)

        if v_x_0 != 0.0:
            initial_theta = math.atan(v_y_0/v_x_0)*180/math.pi
        else:
            initial_theta = 'not a number'
        self.form = Form()

        self.form.range.setText(str(x_final))
        self.form.V_final_x.setText(str(V_final_x))
        self.form.V_final_y.setText(str(V_final_y))
        self.form.t_final.setText(str(t_final))

        self.form.V_highest_x.setText(str(V_highest_x))
        self.form.V_highest_y.setText(str(V_highest_y))
        self.form.x_highest.setText(str(x_highest))
        self.form.y_highest.setText(str(y_highest))
        self.form.t_highest.setText(str(t_highest))

        self.form.initial_theta.setText(str(initial_theta))

        self.form.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())
